// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq-kV4i31Ww60PETEAGQhKaZBi8MV4sW0',
    appId: '1:11472571388:web:64d3514014ada0991e8079',
    messagingSenderId: '11472571388',
    projectId: 'bna-bank',
    authDomain: 'bna-bank.firebaseapp.com',
    storageBucket: 'bna-bank.appspot.com',
    measurementId: 'G-G9N75P5Y19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAADHRSbwFtSh5y01245uN140WihSoHWWA',
    appId: '1:11472571388:android:2c87683fd5ceb6171e8079',
    messagingSenderId: '11472571388',
    projectId: 'bna-bank',
    storageBucket: 'bna-bank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsPIX4X-1khsQ2XVZeb-wEkJ-1eLrhNA',
    appId: '1:11472571388:ios:2f64b7f8382027241e8079',
    messagingSenderId: '11472571388',
    projectId: 'bna-bank',
    storageBucket: 'bna-bank.appspot.com',
    iosBundleId: 'com.example.bankpfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsPIX4X-1khsQ2XVZeb-wEkJ-1eLrhNA',
    appId: '1:11472571388:ios:4e75e9bc12e70a041e8079',
    messagingSenderId: '11472571388',
    projectId: 'bna-bank',
    storageBucket: 'bna-bank.appspot.com',
    iosBundleId: 'com.example.bankpfe.RunnerTests',
  );
}
